#ifndef _ATLAS_H_
#define _ATLAS_H_

#define AU 32

// base atlas
#define B_ATLAS_SLASH (30*AU+1)
#define B_ATLAS_WATER_CENTER (36*AU+3)
#define B_ATLAS_BLOODWATER_CENTER (36*AU+6)


#define B_ATLAS_WHITE_ANGLED_CROSS (30*AU+9)

#define B_ATLAS_PC_BODY_BASE (31*AU+24)
#define B_ATLAS_PC_FACE_FRONT (30*AU+24)
#define B_ATLAS_PC_FACE_LEFT (30*AU+25)
#define B_ATLAS_PC_HAIR_FRONT (29*AU+24)
#define B_ATLAS_PC_HAIR_LEFT (29*AU+25)
#define B_ATLAS_PC_HAIR_BACK (29*AU+26)
#define B_ATLAS_PC_EQUIPMENT_BEAMGUN_BASE (26*AU+0)


#define B_ATLAS_PC_BEAM (31*AU+20)
#define B_ATLAS_ELECTRICITY_AREA (29*AU+1)

#define B_ATLAS_DUMMY (0)

#define B_ATLAS_ITEM_BEAMGUN1 (13*AU+0)
#define B_ATLAS_ITEM_BEAMGUN2 (14*AU+0)
#define B_ATLAS_ITEM_BEAMGUN3 (14*AU+1)
#define B_ATLAS_ITEM_BEAMGUN4 (14*AU+2)
#define B_ATLAS_ITEM_BLASTER (13*AU+1)

#define B_ATLAS_ITEM_HP_POTION (13*AU+3)
#define B_ATLAS_ITEM_TURRET (13*AU+5)    
#define B_ATLAS_ITEM_APPLE (13*AU+6)
#define B_ATLAS_ITEM_ARTIFACT (13*AU+7)
#define B_ATLAS_ITEM_ENERGY_PARTICLE (13*AU+9)
#define B_ATLAS_ITEM_HYPER_PARTICLE (13*AU+10)
#define B_ATLAS_ITEM_DARK_MATTER_PARTICLE (13*AU+11)
#define B_ATLAS_ITEM_HEAL_BLASTER (13*AU+12)

#define B_ATLAS_ITEM_IRON_PLATE (14*AU+3)
#define B_ATLAS_ITEM_RAREMETAL_CRYSTAL (14*AU+4)
#define B_ATLAS_ITEM_BATTERY1 (14*AU+5)
#define B_ATLAS_ITEM_BATTERY2 (14*AU+13)
#define B_ATLAS_ITEM_BRICK_PANEL (14*AU+8)
#define B_ATLAS_ITEM_SHIELD (14*AU+9)
#define B_ATLAS_ITEM_ACCELERATOR (14*AU+10)
#define B_ATLAS_ITEM_WIDE  (14*AU+11)
#define B_ATLAS_ITEM_SHOVEL (14*AU+12)

    
#define B_ATLAS_GRID_CURSOR_BRIGHT (28*AU+0)
#define B_ATLAS_GRID_CURSOR_DARK (28*AU+6)

#define B_ATLAS_BELT_OFF (28*AU+1)
#define B_ATLAS_BELT_ON (28*AU+2)
#define B_ATLAS_BELT_RED (28*AU+14)

#define B_ATLAS_GAUGE_LEFT (28*AU+3)
#define B_ATLAS_GAUGE_CENTER (28*AU+4)
#define B_ATLAS_GAUGE_RIGHT (28*AU+5)

#define B_ATLAS_WINDOW_FRAME_BASE (32*AU+3)
#define B_ATLAS_IDCARD_FRAME_BASE (32*AU+0)

    
#define B_ATLAS_CELL_BASE (22*AU+16)
#define B_ATLAS_SOIL_BASE (23*AU+16)
#define B_ATLAS_ROCK_BASE (24*AU+16)    

#define B_ATLAS_WORM_NORMAL_BASE (17*AU+1)
#define B_ATLAS_WORM_SHOOTER_BASE (17*AU+2)
#define B_ATLAS_WORM_EGG (17*AU+3)



#define B_ATLAS_POISONBALL_BASE (19*AU+0)

#define B_ATLAS_FLYER_SHADOW (30*AU+2)

#define B_ATLAS_BLASTER_EXPLOSION (30*AU+3)
#define B_ATLAS_BLASTER_FRAGMENT_BASE (30*AU+4)

#define B_ATLAS_RIPE_TREE ( 38*AU+0)

#define B_ATLAS_WHITE_FILL (30*AU+6)
#define B_ATLAS_BLACK_FILL (31*AU+6)
#define B_ATLAS_WHITE_CROSS (30*AU+7)
#define B_ATLAS_ELECTRO (30*AU+8)

#define B_ATLAS_POLE_STEM (18*AU+0)
#define POLE_STEM_Y_DIFF 11

#define B_ATLAS_UP_ARROW (28*AU+9)
#define B_ATLAS_RIGHT_ARROW (28*AU+10)
#define B_ATLAS_DOWN_ARROW (28*AU+11)
#define B_ATLAS_LEFT_ARROW (28*AU+12)
#define B_ATLAS_LONG_ARROW (28*AU+13)
#define B_ATLAS_TRASH_ICON (28*AU+15)


#define B_ATLAS_SPARIO (38*AU+11)
#define B_ATLAS_HYPER_SPARIO (38*AU+12)

#define B_ATLAS_SIG (36*AU+12)

#define B_ATLAS_BELO_BASE (37*AU+11)

#define B_ATLAS_WARP_EFFECT_BASE (19*AU+6)

//
#define B_ATLAS_CABLE_INACTIVE_LR (26*AU+11)
#define B_ATLAS_CABLE_INACTIVE_LD (26*AU+12)
#define B_ATLAS_CABLE_ACTIVE_LR (26*AU+13)
#define B_ATLAS_CABLE_ACTIVE_LD (26*AU+14)

#define B_ATLAS_FLAG_BASE (20*AU+0)
#define B_ATLAS_HP_PARTICLE (21*AU+5)
#define B_ATLAS_HYPERSPARK_BASE (20*AU+2)


#define B_ATLAS_MICROBE_PARTICLE (13*AU+8)
#define B_ATLAS_WEED_SEED (14*AU+6)
#define B_ATLAS_TREE_SEED (14*AU+7)

#define B_ATLAS_VENT_NORMAL (22*AU)
#define B_ATLAS_VENT_EXPLODING (22*AU+1)

#define B_ATLAS_FIREGEN_BASE (22*AU+2)
#define B_ATLAS_STRAIGHT_FIREBALL (29*AU+4)
#define B_ATLAS_FIRE (29*AU+6)

#define B_ATLAS_FIRECOPTER (17*AU+4)
#define B_ATLAS_ROUND_FIRE (29*AU+3)

#define B_ATLAS_TUNDRA_TREE (23*AU+0)
#define B_ATLAS_SNOWGROUND_BASE (37*AU+2)
#define B_ATLAS_ICE (36*AU+5)
     
#define B_ATLAS_SNOWSLIME (18*AU+14)
#define B_ATLAS_SNOWBALL (20*AU+9)


#define B_ATLAS_LIGHTBLUE_CIRCLE (27*AU+0)
#define B_ATLAS_LIGHTGREEN_CIRCLE (27*AU+1)
#define B_ATLAS_ORANGE_CIRCLE (27*AU+2)
#define B_ATLAS_RED_CIRCLE (27*AU+3)
    
// Structures on the ground 
#define B_ATLAS_DEROTA (34*AU+11)
#define B_ATLAS_CAGE (34*AU+12)
#define B_ATLAS_MONO_EYE_OPEN (34*AU+13)
#define B_ATLAS_MONO_EYE_CLOSED (34*AU+14)
#define B_ATLAS_COMBI_EYE_OPEN (35*AU+13)
#define B_ATLAS_COMBI_EYE_CLOSED (35*AU+14)
#define B_ATLAS_PANEL_EYE_OPEN (36*AU+13)
#define B_ATLAS_PANEL_EYE_CLOSED (36*AU+14)
#define B_ATLAS_ROUND_EYE_OPEN (37*AU+13)
#define B_ATLAS_ROUND_EYE_CLOSED (37*AU+14)
#define B_ATLAS_SHIELD_EYE (33*AU+14)
#define B_ATLAS_CHASER_EYE_OPEN (38*AU+13)
#define B_ATLAS_CHASER_EYE_CLOSED (38*AU+14)
#define B_ATLAS_BARRIERGEN (35*AU+12)
#define B_ATLAS_BARRIER_LR (32*AU+13)
#define B_ATLAS_BARRIER_CROSS (32*AU+14)    
#define B_ATLAS_BUILDER_EYE_OPEN (39*AU+13)
#define B_ATLAS_BUILDER_EYE_CLOSED (39*AU+14)
#define B_ATLAS_HYPERGEN (38*AU+10)
#define B_ATLAS_FLYGEN (18*AU+11)
#define B_ATLAS_COPTERGEN (18*AU+12)
#define B_ATLAS_SLIMEGEN (18*AU+13)

#define B_ATLAS_BIRD_BASE (18*AU+6)

#define B_ATLAS_TORNADO_BASE (20*AU+10)

#define B_ATLAS_BIRDGEN (18*AU+15)
#define B_ATLAS_SHRIMP (17*AU+5)
#define B_ATLAS_SHRIMP_DEBRIS (17*AU+6)


#define B_ATLAS_IVY_LD (39*AU+0)
#define B_ATLAS_IVY_RD (39*AU+1)
#define B_ATLAS_IVY_RU (39*AU+2)
#define B_ATLAS_IVY_LU (39*AU+3)
#define B_ATLAS_IVY_LR (39*AU+4)
#define B_ATLAS_IVY_UD (39*AU+5)
#define B_ATLAS_IVY_SINGLE (40*AU+0)
#define B_ATLAS_IVY_R (40*AU+1)
#define B_ATLAS_IVY_L (40*AU+2)
#define B_ATLAS_IVY_D (40*AU+3)
#define B_ATLAS_IVY_U (40*AU+4)

#define B_ATLAS_BOMBFLOWER_NORMAL (40*AU+7)
#define B_ATLAS_BOMBFLOWER_MAD (40*AU+6)
#define B_ATLAS_BOMBFLOWER_SEED (40*AU+8)

#define B_ATLAS_BEEHIVE_NORMAL (41*AU+6)
#define B_ATLAS_BEEHIVE_MAD (41*AU+7)

#define B_ATLAS_BEE_BASE (41*AU+4)

#define B_ATLAS_CORE_LT (37*AU+4)
#define B_ATLAS_CORE_RT (37*AU+5)
#define B_ATLAS_CORE_LD (38*AU+4)
#define B_ATLAS_CORE_RD (38*AU+5)

#define B_ATLAS_CORE_COVER (37*AU+3)
#define B_ATLAS_CORE_CABLE_ACTIVE_BASE (37*AU+6)
#define B_ATLAS_CORE_CABLE_INACTIVE_BASE (38*AU+6)

#define B_ATLAS_GRAY_GOO (38*AU+9)

#define B_ATLAS_PAIRBARRIER_ACTIVE (41*AU+13)
#define B_ATLAS_PAIRBARRIER_INACTIVE (41*AU+14)

#define B_ATLAS_DEFENDER_IN_CAGE (22*AU+10)
#define B_ATLAS_REPAIRER_IN_CAGE (22*AU+11)
#define B_ATLAS_TAKWASHI_IN_CAGE (22*AU+12)
#define B_ATLAS_BUILDER_IN_CAGE (22*AU+13)
#define B_ATLAS_VOIDER_IN_CAGE (22*AU+14)
#define B_ATLAS_CHASER_IN_CAGE (22*AU+15)    

#define B_ATLAS_CLIFF (37*AU+1)

#define B_ATLAS_CRYSTAL_BEAMER_ACTIVE_BASE (23*AU+1)
#define B_ATLAS_CRYSTAL_BEAMER_INACTIVE_BASE (23*AU+5)
#define B_ATLAS_STRAIGHT_BEAM (35*AU+9)



// Moving structures on the ground
#define B_ATLAS_BUILDER_BASE (41*AU+9)


// Flying enemies and bullets
#define B_ATLAS_TAKWASHI (37*AU+10)
#define B_ATLAS_REPAIRER (38*AU+10)
#define B_ATLAS_ZOSHI_BASE ( 39*AU+9)

#define B_ATLAS_TOROID_BASE (19*AU+9)
#define B_ATLAS_HYPERPUTTER_BASE (40*AU+9)

#define B_ATLAS_FLY_BASE (18*AU+9)
#define B_ATLAS_VOIDER (19*AU+4)

#define B_ATLAS_VOLCANIC_BOMB (29*AU+5)

#define B_ATLAS_DEFENDER_BASE (18*AU+4)
#define B_ATLAS_BOUNCER (37*AU+9)

#define B_ATLAS_TELEPORTER_BASE (41*AU+0)

#define B_ATLAS_COREBALL (36*AU+10)

// effects
#define B_ATLAS_SPARK_BASE (31*AU+0)
#define B_ATLAS_SHIELD_WORKING (31*AU+4)
#define B_ATLAS_SMOKE (20*AU+5)
#define B_ATLAS_SNOW_BASE (20*AU+6)
#define B_ATLAS_LEAF_BASE (20*AU+14)
#define B_ATLAS_DIGSMOKE_BASE (21*AU+0)

#define B_ATLAS_CELL_BUBBLE_BASE (24*AU+10)
#define B_ATLAS_EXCHANGE_LINK_BALL_BASE (21*AU+3)


// Frame of fortresses
#define B_ATLAS_ENEMY_FRAME_LEFT_TOP (29*AU+11)
#define B_ATLAS_ENEMY_FRAME_TOP (29*AU+12)
#define B_ATLAS_ENEMY_FRAME_RIGHT_TOP (29*AU+13)
    
#define B_ATLAS_ENEMY_FRAME_LEFT (30*AU+11)
#define B_ATLAS_ENEMY_FRAME_CENTER (30*AU+12)
#define B_ATLAS_ENEMY_FRAME_RIGHT (30*AU+13)

#define B_ATLAS_ENEMY_FRAME_LEFT_BOTTOM (31*AU+11)
#define B_ATLAS_ENEMY_FRAME_BOTTOM (31*AU+12)
#define B_ATLAS_ENEMY_FRAME_RIGHT_BOTTOM (31*AU+13)

#define B_ATLAS_ENEMY_FRAME_LEFT_RIGHT (30*AU+14)
#define B_ATLAS_ENEMY_FRAME_TOP_BOTTOM (30*AU+15)

#define B_ATLAS_ENEMY_EYE_DESTROYED (34*AU+10)


// ascii atlas
#define A_ATLAS_BIG_DIGIT_START (32+16)

#endif
